openapi: 3.0.0
info:
  title: Content API
  version: 1.0.0
paths:
  /v1/locales:
    get:
      summary: List available locales
      responses:
        '200':
          description: ok
  /v1/lessons:
    get:
      summary: List lessons for a locale
      parameters:
        - in: query
          name: locale
          schema:
            type: string
      responses:
        '200':
          description: ok
  /v1/models:
    get:
      summary: List models for a locale
      parameters:
        - in: query
          name: locale
          schema:
            type: string
      responses:
        '200':
          description: ok
