name: gitleaks scan

on:
  push:
    branches: [ main, develop, test ]
  pull_request:
    branches: [ main, develop, test ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run gitleaks
      uses: zricethezav/gitleaks-action@v2
      with:
        args: '--redact --path=.'
